import type OpenAI from "openai";

import {
  fetchCategoryNews,
  type TavilyArticle,
} from "../services/tavily.service.js";
import {
  generateArticleTLDR,
  generateDailyGlance,
  type SummaryLlmConfig,
} from "../services/summary.service.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EnrichedArticle extends TavilyArticle {
  /** Two-sentence TL;DR generated by the LLM. */
  tldr: string;
}

export interface DailyNewsResult {
  /** Aggregated "Daily Glance" summary across all categories. */
  dailySummary: string;
  /** Per-category articles enriched with individual TL;DRs. */
  categorizedNews: Record<string, EnrichedArticle[]>;
}

// ---------------------------------------------------------------------------
// Pipeline
// ---------------------------------------------------------------------------

/**
 * Run the full Tavily-powered daily news pipeline:
 *
 * 1. For each category, search for recent news via Tavily.
 * 2. Generate a per-article TL;DR using the LLM.
 * 3. Aggregate all TL;DRs into a single "Daily Glance" summary.
 */
export async function runDailyNewsPipeline(
  client: OpenAI,
  llmConfig: SummaryLlmConfig,
  categories: string[],
  maxResultsPerCategory = 5
): Promise<DailyNewsResult> {
  const categorizedNews: Record<string, EnrichedArticle[]> = {};
  const tldrOverview: Record<string, string[]> = {};

  for (const category of categories) {
    console.log(`🔍 [tavily] Searching: ${category}`);

    const articles = await fetchCategoryNews(category, maxResultsPerCategory);

    categorizedNews[category] = [];
    tldrOverview[category] = [];

    if (articles.length === 0) {
      console.log(`   ⚠ No Tavily results for "${category}"`);
      continue;
    }

    console.log(`   ↳ ${articles.length} articles found`);

    for (const article of articles) {
      if (!article.content || article.content.trim().length === 0) {
        console.log(`   ⚠ Skipping article with empty content: ${article.title}`);
        continue;
      }

      const tldr = await generateArticleTLDR(client, llmConfig, article.content);
      const enriched: EnrichedArticle = { ...article, tldr };

      categorizedNews[category].push(enriched);
      tldrOverview[category].push(tldr);
    }
  }

  // Only generate the daily glance if we have at least one TL;DR
  const totalTLDRs = Object.values(tldrOverview).reduce(
    (sum, arr) => sum + arr.length,
    0
  );

  let dailySummary: string;
  if (totalTLDRs === 0) {
    dailySummary =
      "No articles were available from Tavily today. Please check your categories and API key.";
  } else {
    console.log(`\n📝 Generating Daily Glance from ${totalTLDRs} TL;DRs…`);
    dailySummary = await generateDailyGlance(client, llmConfig, tldrOverview);
  }

  return { dailySummary, categorizedNews };
}
